# Generated by Django 2.1.2 on 2018-10-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
