# Generated by Django 2.1.2 on 2019-01-24 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-start_datetime'], 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.CharField(max_length=255, verbose_name='activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='project',
            field=models.CharField(db_index=True, max_length=255, verbose_name='project'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='start time'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
